### ISSUE TITLE
Feature Request: Add an Option for Custom Base URL

### ISSUE THREAD

**Issue by chendongde310** [muhammedsaidckr/flarum-chatgpt#2]
Hello,
﻿
Thank you for the amazing project! I have a feature request: could you add an option to configure a custom ChatGPT API URL instead of using the default api.openai.com? This would be useful in cases where users need to use alternative API endpoints or self-hosted versions of the OpenAI API.
﻿
This feature would add more flexibility for different deployment environments.
﻿
Looking forward to your thoughts!
﻿
Best regards

**Comment by muhammedsaidckr** [comment]
Thank you for your feature request and for your kind words about the project! We appreciate your input on making the tool more flexible.

Adding an option to configure a custom ChatGPT API URL is an interesting suggestion. It could indeed provide more flexibility for users with different deployment needs or those using alternative API endpoints.

Thank you again for your suggestion and for taking the time to contribute to improving the project. We'll keep you updated on the status of this feature request.

**Comment by 2693551060** [comment]
I also need this feature. Thank you

**Comment by muhammedsaidckr** [comment]
https://github.com/muhammedsaidckr/flarum-chatgpt/releases/tag/v1.2.5

**Comment by chendongde310** [comment]
Hello,

Thank you for your prompt response and for considering my feature request!

After updating to the latest version (v1.2.5) of the Flarum ChatGPT extension, I encountered a boot error in Flarum. The application fails to start properly, and I see several HTTP 500 errors in the log file when trying to access the admin panel or make API requests.

Here are some relevant log entries:

```
113.248.232.44 - - [07/Sep/2024:15:20:31 +0800] "GET /admin HTTP/1.1" 500 92 "http://app.ue5box.com:40020/admin"
113.248.232.44 - - [07/Sep/2024:15:23:24 +0800] "GET /api/discussions?include=user%2ClastPostedUser%2Ctags%2Ctags.parent%2CfirstPost&sort&page%5Boffset%5D=0 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
113.248.232.44 - - [07/Sep/2024:15:23:24 +0800] "GET /api/users/2 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
113.248.232.44 - - [07/Sep/2024:15:23:29 +0800] "GET /api/discussions?include=user%2ClastPostedUser%2Ctags%2Ctags.parent%2CfirstPost&filter%5Bsubscription%5D=following&sort&page%5Boffset%5D=0 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/following"
113.248.232.44 - - [07/Sep/2024:15:23:32 +0800] "GET /admin HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
```

It seems there might be an issue with the latest release. Could you please take a look at this error? Any guidance on resolving this issue would be greatly appreciated. In the meantime, I have reverted to the previous version, which is working fine.

Thank you for your attention to this matter and for your continuous efforts in improving the project!

Best regards

**Comment by muhammedsaidckr** [comment]
> Hello,
> 
> Thank you for your prompt response and for considering my feature request!
> 
> After updating to the latest version (v1.2.5) of the Flarum ChatGPT extension, I encountered a boot error in Flarum. The application fails to start properly, and I see several HTTP 500 errors in the log file when trying to access the admin panel or make API requests.
> 
> Here are some relevant log entries:
> 
> ```
> 113.248.232.44 - - [07/Sep/2024:15:20:31 +0800] "GET /admin HTTP/1.1" 500 92 "http://app.ue5box.com:40020/admin"
> 113.248.232.44 - - [07/Sep/2024:15:23:24 +0800] "GET /api/discussions?include=user%2ClastPostedUser%2Ctags%2Ctags.parent%2CfirstPost&sort&page%5Boffset%5D=0 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
> 113.248.232.44 - - [07/Sep/2024:15:23:24 +0800] "GET /api/users/2 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
> 113.248.232.44 - - [07/Sep/2024:15:23:29 +0800] "GET /api/discussions?include=user%2ClastPostedUser%2Ctags%2Ctags.parent%2CfirstPost&filter%5Bsubscription%5D=following&sort&page%5Boffset%5D=0 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/following"
> 113.248.232.44 - - [07/Sep/2024:15:23:32 +0800] "GET /admin HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
> ```
> 
> It seems there might be an issue with the latest release. Could you please take a look at this error? Any guidance on resolving this issue would be greatly appreciated. In the meantime, I have reverted to the previous version, which is working fine.
> 
> Thank you for your attention to this matter and for your continuous efforts in improving the project!
> 
> Best regards

Did you clear the cache after update

**Comment by chendongde310** [comment]
> > Hello,
> > Thank you for your prompt response and for considering my feature request!
> > After updating to the latest version (v1.2.5) of the Flarum ChatGPT extension, I encountered a boot error in Flarum. The application fails to start properly, and I see several HTTP 500 errors in the log file when trying to access the admin panel or make API requests.
> > Here are some relevant log entries:
> > ```
> > 113.248.232.44 - - [07/Sep/2024:15:20:31 +0800] "GET /admin HTTP/1.1" 500 92 "http://app.ue5box.com:40020/admin"
> > 113.248.232.44 - - [07/Sep/2024:15:23:24 +0800] "GET /api/discussions?include=user%2ClastPostedUser%2Ctags%2Ctags.parent%2CfirstPost&sort&page%5Boffset%5D=0 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
> > 113.248.232.44 - - [07/Sep/2024:15:23:24 +0800] "GET /api/users/2 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
> > 113.248.232.44 - - [07/Sep/2024:15:23:29 +0800] "GET /api/discussions?include=user%2ClastPostedUser%2Ctags%2Ctags.parent%2CfirstPost&filter%5Bsubscription%5D=following&sort&page%5Boffset%5D=0 HTTP/1.1" 500 92 "http://app.ue5box.com:40020/following"
> > 113.248.232.44 - - [07/Sep/2024:15:23:32 +0800] "GET /admin HTTP/1.1" 500 92 "http://app.ue5box.com:40020/"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems there might be an issue with the latest release. Could you please take a look at this error? Any guidance on resolving this issue would be greatly appreciated. In the meantime, I have reverted to the previous version, which is working fine.
> > Thank you for your attention to this matter and for your continuous efforts in improving the project!
> > Best regards
> 
> Did you clear the cache after update

Yes, I have tried rebuilding Flarum a few times and even after installing the new plugin, it will reproduce

**Comment by muhammedsaidckr** [comment]
@chendongde310 can you share the flarum logs please. It is under the storage/logs folder.

**Comment by chendongde310** [comment]
[flarum-2024-09-07.log](https://github.com/user-attachments/files/16917670/flarum-2024-09-07.log)


> @chendongde310 can you share the flarum logs please. It is under the storage/logs folder.

**Comment by muhammedsaidckr** [comment]
@chendongde310 There is a user id field in the extension settings. Which user id do you use. Is the user exists with that ID.
